describe('TT e2e', () => {
    it('TT Personal', () => {
    cy.visit('https://fuw-dev.azurewebsites.net/total-term')
    cy.get('.btn-primary').click()
    cy.get('#FirstName').type('Zvi')
    cy.get('#LastName').type('Weiss')
    cy.get('#DateofBirth').type('01/01/1980')
    cy.get('#Street').type('3 Main Street')
    cy.get('#City').type('Anycity')
    cy.get('#State').type('OH')
    cy.get('#Zip').type('10878')
    cy.get('#PrimaryTelephoneNumber').type('845-667-1980')
    cy.get('#EmailAddress').type('zvweiss@gmail.com')
    cy.get('#PlaceofBirthCountry').type('United States')
    cy.get('#USCitizenYes-button').type('Yes')
    cy.get('#MilitaryPersonnelNo-button').type('Yes')
    cy.get('.btn-primary').click()
   })
  })
