describe('TT e2e', () => {
    it('TT Personal', () => {
    cy.visit('https://fuw-dev.azurewebsites.net/total-term')
    cy.get('.btn-primary').click()
    cy.get('#FirstName').type('Zvi')
    cy.get('#LastName').type('Weiss')
    cy.get('#DateofBirth').type('01/01/1980')
    cy.get('#Street').type('3 Main Street')
    cy.get('#City').type('Anycity')
    cy.get('#State').type('OH')
    cy.get('#Zip').type('10878')
    cy.get('#PrimaryTelephoneNumber').type('845-667-1980')
    cy.get('#EmailAddress').type('zvweiss@gmail.com')
    cy.get('#PlaceofBirthCountry').select('Austria')
    cy.get('#USCitizenYes-button').type('Yes')
    cy.get('#MilitaryPersonnelNo-button').type('Yes')
    cy.get('.btn-primary').click()
    cy.get('#Occupation').type('Welder')
    cy.get('#AnnualIncome').type('123000')
    cy.get('#NetWorth').type('399999')
    cy.get('#CoverageAmount').select('$750,000')
    cy.get('#TermLength').get('#mat-radio-10').click()
    cy.get('.btn-primary').click()
    cy.get('#LifeApplicationNo').type('No')
    cy.get('#ExistingLifeInsuranceNo').type('No')
    cy.get('#ReplacementInsuranceNo').type('No')
    cy.get('#ReplacementInsurancePremiumsNo-button').type('No')
    cy.get('#NewCoverage').clear().type('800000')
    cy.get('.btn-primary').click()
   })
  })
